

= Java Decompiler IntelliJ IDEA Plugin Changelog


[[releasenotes]]
== Release notes

ifndef::revnumber[:revnumber: Work in progress]
// revnumber is the current project version
=== {revnumber}

- Switch the build to gradle
- Support IJ 2019.2
- Upgrade support to JD-Core 0.7.1

=== 0.6

Updated to work with the new IntelliJ IDEA 13.1 extension point.


=== 0.5

- Adds a new toggle to escape the unicode chars.
- The long awaited realignment feature is there, provided the classes are compiled
  with line numbers. https://bitbucket.org/bric3/jd-intellij/issue/14[JD-IntelliJ Issue 14]
- JD-IntelliJ native code should no longer crash the running JVM.
  https://bitbucket.org/bric3/jd-intellij/issue/7[JD-IntelliJ Issue 7] & https://bitbucket.org/bric3/jd-intellij/issue/8[JD-IntelliJ Issue 8]

=== 0.4.1

- Packages a more recent guava version as IntelliJ 10.5 guava dependency is too old.
  https://bitbucket.org/bric3/jd-intellij/issue/17[JD-IntelliJ Issue 17]
- There is a known issue that could crashes the VM on some 64bit Linux boxes.

=== 0.4

- Fixes the wrong clickable references (ctrl-click / cmd-click), Still not perfect though
  as file's local references don't work. For more development information about the issue,
  see IDEA-100029, https://bitbucket.org/bric3/jd-intellij/issue/6[JD-IntelliJ Issue 6]
- There is a known issue that could crashes the VM on some 64bit Linux boxes.

=== 0.3

- Fixes an undesirable effect for people using the Flex SDK, see IDEA-93429
- Note that references in the editor are not correctly clickable (ctrl-click / cmd-click),
  this does seem to be a bug in IntelliJ IDEA itself; see IDEA-100029
- There is a known issue that could crashes the VM on some 64bit Linux boxes.

=== 0.2

- Now fallback to IntelliJ decompiler when JD cannot decompile normally for some rare
  class file. Before an assertion error was reported in IntelliJ.
- There is a known issue that could crashes the VM on some 64bit Linux boxes.

=== 0.1

- First release. Using JD-Core 0.6.1
- There is a known issue that could crashes the VM on some 64bit Linux boxes.

.Legal Stuff
JD-IntelliJ is free for non-commercial use. This means that JD-IntelliJ shall not be
included or embedded into commercial software products. Nevertheless, this project may
be freely used for personal needs in a commercial or non-commercial environments.
Website : https://java-decompiler.github.io/
Sources : https://github.com/bric3/jd-intellij

.For Windows users, you might need to install the prerequisites.
The native library, included into JD-Eclipse for Windows, has been built with Microsoft Visual C++ 2008 Express Edition. Some runtime components of Visual C++ Libraries are required to run the decompiler. If they are missing you can download and install them from the Microsoft Web site :
Microsoft Visual C++ 2008 SP1 Redistributable Package (x86)
Microsoft Visual C++ 2008 SP1 Redistributable Package (x64)
