name: Java CI

on:
  push:
    paths-ignore:
      - '*.adoc'
      - '.editorconfig'
      - '.gitignore'
      - '.tool-versions'
      - '*.png'
    branches:
      - 'master'
  pull_request:
    paths-ignore:
      - '*.adoc'
      - '.editorconfig'
      - '.gitignore'
      - '.tool-versions'
      - '*.png'

jobs:
  gradleValidation:
    name: Gradle Wrapper Validation
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v2
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.3

  build:
    needs: gradleValidation
    name: Build plugin
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Fetch sources
        uses: actions/checkout@v2

      - name: Restore gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      - name: Restore Gradle wrapper cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build Java Decompiler Plugin with Gradle
        run: ./gradlew check verifyPlugin buildPlugin

      - name: Upload artifact for next job
        uses: actions/upload-artifact@v2
        with:
          name: Jd-intellij-plugin-artifact
          path: ./build/distributions/${{ needs.build.outputs.artifact }}


  verify:
    needs: build
    name: Verify Plugin
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Fetch Sources
        uses: actions/checkout@v2

      - name: Restore gradle cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle', '**/*.gradle.kts', 'gradle.properties') }}

      - name: Restore Gradle wrapper cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      - name: Restore plugin verifier IDEs Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.properties.outputs.pluginVerifierHomeDir }}/ides
          key: ${{ runner.os }}-plugin-verifier-${{ steps.properties.outputs.ideVersions }}

      - name: Verify Plugin
        run: ./gradlew runPluginVerifier -Pplugin.verifier.home.dir=${{ steps.properties.outputs.pluginVerifierHomeDir }}